# Generated by Django 4.1 on 2022-09-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("username", models.CharField(blank=True, max_length=32, null=True)),
                ("first_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "language_code",
                    models.CharField(
                        blank=True,
                        help_text="Telegram client's lang",
                        max_length=8,
                        null=True,
                    ),
                ),
                ("deep_link", models.CharField(blank=True, max_length=64, null=True)),
                ("is_blocked_bot", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "chat_status",
                    models.CharField(
                        blank=True, default=None, max_length=256, null=True
                    ),
                ),
                (
                    "chat_data",
                    models.CharField(
                        blank=True, default=None, max_length=256, null=True
                    ),
                ),
            ],
            options={"ordering": ("-created_at",), "abstract": False,},
        ),
        migrations.CreateModel(
            name="MoneyRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=256)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("is_done", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.user"
                    ),
                ),
            ],
        ),
    ]
